---
# Set up homebrew and manage most things through homebrew packages.

- name: Check for a preexisting homebrew installation.
  command: brew -v
  ignore_errors: true
  register: brewcheck

- name: Fetch the homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: /tmp/install-homebrew
    sha256sum: 85fbdee4fd54ca493b2ec4add3f36496447706f14bc30569bb73fa82be164ef3
  register: homebrew-installer
  when: brewcheck | failed

- name: Install homebrew
  command: ruby /tmp/install-homebrew
  when: (brewcheck | failed) and (homebrew-installer | changed)

- name: Homebrew packages
  homebrew: name={{ item }} state=latest
  with_items:
  - autoconf
  - bash-completion
  - coreutils
  - readline
  - openssl
  - gettext
  - dos2unix
  - pcre
  - pkg-config
  - watch
  - watchman
  - cunit
  - ragel
  - lemon
  - gmp
  - gdbm
  - cowsay
  - ssh-copy-id
  - git
  - hub
  - mercurial
  - sqlite
  - redis
  - boot2docker
  - docker
  - node
  - go
  - ghc
  - cabal-install

- name: Ruby homebrew packages
  homebrew: name={{ item }} state=latest
  with_items:
  - rbenv
  - ruby-build
  tags: ["ruby"]

- name: Install Ruby through rbenv
  command: rbenv install {{ ruby_version }} creates=/usr/local/var/rbenv/versions/{{ ruby_version }}/bin/ruby
  tags: ["ruby"]

- name: Ruby gems
  gem: name={{ item }} state=latest
  with_items: ruby_gems
  tags: ["ruby"]

- name: Python homebrew package
  homebrew: name=python state=latest
  tags: ["python"]

- name: Python packages
  pip: name={{ item }} state=latest
  sudo: true
  with_items: python_packages
  tags: ["python"]

- name: Rust
  include: reusable/rust.yml sha_cmd=shasum sha_args='-a 256'
