---
# Install Docker on an Ubuntu or Mint system.

- name: ensure Grub passes the right command-line arguments to the kernel
  lineinfile:
    dest: /etc/default/grub
    backrefs: yes
    regexp: ^GRUB_CMDLINE_LINUX="[^"]*"
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
    state: present
  sudo: yes

- name: see if HTTPS transport is already present
  stat: path=/usr/lib/apt/methods/https get_md5=false
  register: https_transport_file

- name: ensure HTTPS transport is available to apt
  apt: name=apt-transport-https state=latest update_cache=yes cache_valid_time=3600
  sudo: yes
  when: not https_transport_file.stat.exists

- name: ensure the docker apt key is trusted
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
    state: present
  sudo: yes

- name: ensure the docker apt repository is present
  apt_repository:
    repo: deb https://get.docker.com/ubuntu docker main
    state: present
  sudo: yes

- name: apt prerequisites
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
  - git
  - vim
  - curl
  - wget
  - python
  - cgroup-lite
  - apparmor
  - lxc-docker
  sudo: yes
