#!/usr/bin/env bash
#
# bootstrap installs things.

# Just disable this for now so Strap can do its thing
exit 0

DOTFILES_ROOT=$(cd $(dirname $0)/.. && pwd)

set -euo pipefail

source script/include/output.sh
source script/include/probe.sh
